name: 🔍 MSRV Check

on: [push, pull_request]

jobs:
  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Get MSRV from package metadata
      - name: Get MSRV from package metadata
        id: metadata
        run: |
          cargo metadata --no-deps --format-version 1 |
              jq -r '"msrv=" + (.packages[] | select(.name == "libyml")).rust_version' >> $GITHUB_ENV

      # Install the MSRV Rust version
      - name: Install Rust (${{ env.msrv }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.msrv }}

      # Run cargo check to verify compatibility
      - name: Test with MSRV
        run: cargo check -p libyml --verbose
